site_name: "@visisoft/staticland"
repo_url: https://github.com/semmel/StaticLand
site_dir: html-docs
docs_dir: doc
nav:
  - Welcome: index.md
  - About Cancelables: cancelable.md
  - Cancelable: cancelable-api.md
  - maybe.md
  - promise.md
  - list.md
  - transformations.md
  - io.md
  - changelog.md
  - license.md
meta:
  version: !!python/object/apply:os.getenv ["npm_package_version"]
  name: !!python/object/apply:os.getenv ["npm_package_name"]
markdown_extensions:
  - pymdownx.tilde
  - pymdownx.tasklist
  - markdown.extensions.footnotes
  - def_list
  - pymdownx.emoji
  - pymdownx.snippets
  - plantuml_markdown
plugins:
  - include-markdown
  - search
  - macros
theme: material
