site_name: "@visisoft/staticland"
site_dir: html-docs
docs_dir: doc
nav:
  - Welcome: index.md
  - About Cancelables: cancelable.md
  - Cancelable: cancelable-api.md
  - maybe.md
  - promise.md
  - transformations.md
  - io.md
  - changelog.md
  - license.md
markdown_extensions:
  - pymdownx.tilde
  - pymdownx.tasklist
  - markdown.extensions.footnotes
  - def_list
  - pymdownx.emoji
  - pymdownx.snippets
  - plantuml_markdown
plugins:
  - include-markdown
theme: material
